- hosts: all
  gather_facts: yes
#  roles:
#  - { role: andrewrothstein.java-oracle-jre }
  tasks:
  - name: install unzip
    yum:
      name: unzip
      state: present
    become: yes
  - name: install httpd
    yum:
      name: httpd
      state: present
    become: yes
  - name: enable httpd
    service:
      name: httpd
      enabled: yes
    become: yes
  - name: download and extract awscli
    unarchive: 
      src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
      dest: /tmp
      remote_src: yes
  - name: install awscli
    shell: /tmp//awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    become: yes
  - name: install gettag.sh
    copy:
      src: files/gettag.sh
      dest: /usr/local/bin/gettag.sh
      mode: 0755
    become: yes
