- hosts: all
  gather_facts: yes
  tasks:
  - name: install unzip
    yum:
      name: unzip
      state: present
    become: yes
  - name: install git
    yum:
      name: git
      state: present
    become: yes
  - name: install epel
    yum:
      name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
    become: yes
  - name: install python-pip
    yum:
      name: python-pip
      state: present
    become: yes
  - name: download Scout2
    git:
      repo: 'https://github.com/nccgroup/Scout2'
      dest: /tmp/Scout2
  - name: install Scout2
    shell: cd /tmp/Scout2 && pip install -r requirements.txt && python setup.py install
    become: yes
  - name: crontab for Scout2
    cron:
      name: "Scout2"
      special_time: hourly
      job: "/usr/bin/Scout2 --force --no-browser"
  - name: disable chronyd service
    service:
      name: chronyd
      state: stopped
      enabled: no
    become: yes
  - name: install ntp
    yum:
      name: ntp
      state: present
    become: yes
  - name: Write ntp.conf
    vars:
      ntp_servers:
        - 0.pool.ntp.org
        - 1.pool.ntp.org
        - 2.pool.ntp.org
    template:
      src: "ntp.conf.j2"
      dest: "/etc/ntp.conf"
      mode: 0644
    become: yes
  - name: enable ntpd
    service:
      name: ntpd
      enabled: yes
    become: yes
  - name: download and extract awscli
    unarchive: 
      src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
      dest: /tmp
      remote_src: yes
  - name: install awscli
    shell: /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    become: yes
  - name: install gettag.sh
    copy:
      src: files/gettag.sh
      dest: /usr/local/bin/gettag.sh
      mode: 0755
    become: yes
  - name: download and extract cloudwatch agent
    unarchive:
      src: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
      dest: /tmp
      remote_src: yes
  - name: install cloudwatch agent
    shell: ./install.sh
    args:
      chdir: /tmp
    become: yes
  - name: install cloudwatch agent config file
    copy:
      src: files/amazon-cloudwatch-agent-jump.json
      dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
    become: yes
  - name: start cloudwatch agent
    shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
    become: yes
  - name: clean log files
    file:
      path: /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
      state: absent
    become: yes
